### ISSUE TITLE
Warning shown when ng serve --aot 

### ISSUE THREAD

**Issue by mac10046** [juan-manuel-alberro/angular-sweetalert2#4]
WARNING in ./node_modules/angular-sweetalert-service/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (E:\AbdealiTemp\adviserpanel\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (E:\AbdealiTemp\adviserpanel\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (E:\AbdealiTemp\adviserpanel\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (E:\AbdealiTemp\adviserpanel\node_modules\webpack\lib\Compiler.js:502:17)
    at E:\AbdealiTemp\adviserpanel\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (E:\AbdealiTemp\adviserpanel\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (E:\AbdealiTemp\adviserpanel\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/angular-sweetalert-service/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular-sweetalert-service/js/service/sweetalert2.service.js
 @ ./src/app/pages/adviser/dashboard/dashboard.module.ngfactory.js
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/angular-sweetalert-service/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (E:\AbdealiTemp\adviserpanel\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (E:\AbdealiTemp\adviserpanel\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (E:\AbdealiTemp\adviserpanel\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (E:\AbdealiTemp\adviserpanel\node_modules\webpack\lib\Compiler.js:502:17)
    at E:\AbdealiTemp\adviserpanel\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (E:\AbdealiTemp\adviserpanel\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (E:\AbdealiTemp\adviserpanel\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/angular-sweetalert-service/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular-sweetalert-service/js/service/sweetalert2.service.js
 @ ./src/app/pages/adviser/dashboard/dashboard.module.ngfactory.js
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by Manikandan-CloudevTech** [comment]
Same issue for me. Any solutions..?

**Comment by Temsi** [comment]
This is still an issue.
